### ISSUE TITLE
Import modules in same folder

### ISSUE THREAD

**Issue by piac** [mcneel/ghpython#12]
It might be useful to be able to import modules that  are in the same folder as the ghx file (add ghx folder to search path)

**Comment by bengolder** [comment]
I agree. I think it might also make sense to add the Components Folder to sys.path, and that way people could install python packages in their Components Folder for general use in ghpython.

**Comment by saeranv** [comment]
I'd really like this too! The last comment on this was two years ago - has any there been progress made on this?

**Comment by piac** [comment]
This should already work in the last release. Please let me know if you notice that there's anything strange or that does not work. Thanks, Giulio
