### ISSUE TITLE
rs.TransformObjects does not convert to ID

### ISSUE THREAD

**Issue by scotttd** [mcneel/ghpython#13]
rs.TransformObjects( geo, xform, True ) does not work on geometry input from an outside component.   is a Brep or any other geometry type. 

Specific example:
Create a GHpython component with the x input as a Box or any Brep.
## Code: 
# sample script to show how to use this component and rhinoscriptsyntax

import math
import rhinoscriptsyntax as rs

geo = x
cplane = rs.WorldXYPlane()
xform = rs.XformRotation2(y, cplane[3], cplane[0])
## rs.TransformObjects( geo, xform, True )

I realize if I use the code: 

geo=ghdoc.Objects.AddBrep(x) 

to create an ID I can use in rs.TransformObjects, but that line should not be required.

**Comment by piac** [comment]
This is a Rhino.Python bug/feature request. I reposted it there.
https://github.com/mcneel/rhinopython/issues/38
