### ISSUE TITLE
Marshaling a Circle

### ISSUE THREAD

**Issue by scotttd** [mcneel/ghpython#20]
If I create a circle using rs.addcircle or rs.addcircle3pt should create a Rhino Circlecurve.  If I try and output that from GHpython it is not marshaled as a Circle in Grasshopper.

**Comment by piac** [comment]
Hi Scott,
I opened a thread on the Grasshopper forum: http://www.grasshopper3d.com/forum/topics/ghpython-marshalling-discourse
Please let me know if this helps.
