### ISSUE TITLE
Mashalling an arc

### ISSUE THREAD

**Issue by scotttd** [mcneel/ghpython#21]
If I use rs.AddArc, rs.AddArc3pt or rs.AddArcPtTanPt then I should get an ArcCurve.  When i pass this out ghpython, I do not get an Arc.  Can we marshal an arc from the guiid?

**Comment by piac** [comment]
Hi Scott,
I opened a thread on the Grasshopper forum: http://www.grasshopper3d.com/forum/topics/ghpython-marshalling-discourse
Please let me know if this helps.
