### ISSUE TITLE
Coerce3dPoint & Coerce3dVector do not accept Vector3f

### ISSUE THREAD

**Issue by AvdHarten** [mcneel/ghpython#24]
When you run mesh face normals through a function that calls Coerce3dPoint or Coerce3dVector, you get an exception.

This affects many functions from the RhinoScriptSyntax module. A workaround is to call Rhino.Geometry.Vector3f.ToString(). These functions work fine with a string version of the vector.

Arthur

**Comment by sbaer** [comment]
done

**Comment by AvdHarten** [comment]
Awesome! And so timely!
