### ISSUE TITLE
gh_python breakage

### ISSUE THREAD

**Issue by bengolder** [mcneel/ghpython#32]
Right now, if I create a new grasshopper definition, and add a ghpython component, the fresh component returns the following error:

```
Runtime error (MissingMemberException): 'ScopeStorage' object has no attribute 'scriptcontext'
Traceback (most recent call last):
AttributeError: 'ScopeStorage' object has no attribute 'scriptcontext'
```

I've tried changing the rhinoscriptsyntax usage to all different settings, and it appears to occur without regard to any input code.
First began after I copied and pasted a python component from an existing definition into a new definition.

Now to try other basic tactics (restart Rhino, computer, etc.) ...

**Comment by bengolder** [comment]
restarting rhino eliminated the error.

**Comment by piac** [comment]
Thanks for the report. I'll try to see what is going on.
I think it did not happen before, I'll try to reproduce it.

**Comment by bengolder** [comment]
Sorry, important details: this happened in the latest grasshopper (0.8.0063) using Rhino 5 32-bit. I also had Rhino 5 64-bit open at the same time, but it was sitting idle, without grasshopper open. Both Rhino 5 versions are up-to-date. I had previously run scripts in the 64-bit (not using grasshopper, using RunPythonScript).

**Comment by piac** [comment]
From a sample error that I could find, this is the same bug as #25:  https://github.com/mcneel/ghpython/issues/25
