### ISSUE TITLE
Interface wishes from Mitch

### ISSUE THREAD

**Issue by sbaer** [mcneel/ghpython#37]
Posted on python forum at http://python.rhino3d.com/threads/994-Grasshopper-python-component-suggestion

Hi Giulio,

OK, thanks! Couple of other things - 

1) Once you put your own script in there, the component can't distinguish from no input, insufficient input or incorrect input. With normal GH components, the first two result in an orange component color, the last with a red. With GHPython it's always red until it's correct. I would like to see the component be orange when one or more inputs are disconnected, don't know if that's possible.

2) I would like to be able to prompt the user as what the component is expecting at the inputs and and returning at the outputs - right now all you have is "Script variable X..." , but the standard components give you the actual description of the data it is expecting - so that would imply in the input/output manager would have a place to type in these names, and then they could show up when someone hovers the mouse over the spot.

3) Relative to the above, if a type hint (such as "curve") is given for any input, that the input right click generic "set one data item" changes to the type specific "set one curve"... 

Thanks, --Mitch

**Comment by piac** [comment]
1) Is explained on the forum page http://python.rhino3d.com/threads/994-Grasshopper-python-component-suggestion
2) Is addressed in commit https://github.com/mcneel/ghpython/commit/f23dffee0edb5d909c9beaa8d917b5ee0e71246b
3) Needs further study and changes in Grasshopper
