### ISSUE TITLE
AddText Runtime Error

### ISSUE THREAD

**Issue by sbaer** [mcneel/ghpython#38]
http://python.rhino3d.com/threads/1028-rs.AddText-gives-Runtime-error-(MissingMemberException)

If grasshopper does not have support for the text that this script is supposed to generate, then it may make sense to provide more descriptive exceptions.  Maybe something like
"Text objects are not supported grasshopper, so this python script can not create them"
Of course if text objects are supported, then we just need to fix the function.

**Comment by piac** [comment]
This should be now postponed till Grasshopper supports Text.

**Comment by piac** [comment]
Changed the text to state:

This type of object is not supported in Grasshopper, so this Python script cannot create it. You might want to use 'scriptcontext.doc = Rhino.RhinoDoc.ActiveDoc' to use the Rhino doc, instead? If you do, remember to restore it: 'scriptcontext.doc = ghdoc'.
