### ISSUE TITLE
Hide code input by default

### ISSUE THREAD

**Issue by bengolder** [mcneel/ghpython#40]
A small change that I think would improve presentation and reduce confusion for new users.

**Comment by sbaer** [comment]
I would have to agree on this one.  The code input is also hard to optimize and is probably only rarely really useful.

**Comment by piac** [comment]
I also agree. It probably hides a very nice reason to use Python, but I also came to think it might be a second step, not something useful for a new user. This change will be there in the next release.

**Comment by bengolder** [comment]
fantastic. thanks
