### ISSUE TITLE
Add Grasshopper assembly for easy import

### ISSUE THREAD

**Issue by AndersDeleuran** [mcneel/ghpython#50]
I often import the Grasshopper assembly in order to construct data trees for outputting nested Python lists and such.

In order to do this I usually do this:

import clr; 
clr.AddReference("Grasshopper")
import Grasshopper as gh

While this is not a major problem, it would be great if the Grasshopper assembly was automatically added so I could simply go:

import Grasshopper as gh

Cheers,
Anders

**Comment by bengolder** [comment]
this is a great suggestion

**Comment by piac** [comment]
This is fixed in commit https://github.com/mcneel/ghpython/commit/38cf73f921a436c0f27fd870ea7ab0d706d202e9

**Comment by AndersDeleuran** [comment]
You're a damn rock star Giulio :)

**Comment by bengolder** [comment]
Cool!
