### ISSUE TITLE
ValueErrorException on file open in 0.5.99.0

### ISSUE THREAD

**Issue by AndersDeleuran** [mcneel/ghpython#52]
I noticed a repeatable bug with the latest update 0.5.99.0. Whenever I open a Grasshopper definition containing a GHPython component the component will throw the error message:

Runtime error (ValueErrorException): list.index(item): item not in list
Traceback:
  line 2, in script

Recomputing the definition or updating the component will immediately cause the error to go away. I have noticed the same error occurring while writing code and testing (that is, not when I open the definition). I have however not noticed a pattern yet in how this occurs. Will report back if I do.

Best,

Anders

**Comment by mostaphaRoudsari** [comment]
The same here. I was working on a file all day this morning and it never happened. Then I opened an old file with an old script and it gave me the error. After that every time that I drop one of the Ladybugs components (which are GHPython components) I get the same error.

**Comment by piac** [comment]
Can you send me a definition that shows this problem?
I have a guess on what is causing this, and I'd like to test it.
Thanks!

## 

giulio@mcneel.com

**Comment by mostaphaRoudsari** [comment]
Hi @piac, I sent you an example. Thanks for checking this. -Mostapha

**Comment by piac** [comment]
This should be fixed in the last release
https://github.com/mcneel/ghpython/releases/tag/v0.5.101

**Comment by AndersDeleuran** [comment]
Looks like it. Just tested it on a couple of definitions I've been working on without reproducing the error. Thanks for the quick update. Very cool..
