### ISSUE TITLE
Wish: Editor Font Select

### ISSUE THREAD

**Issue by AndersDeleuran** [mcneel/ghpython#55]
It would be great to have the option to pick the editor font similar to the EditPythonScript editor. 

After having used Eclipse and recently picking up Sublime Text 2 I find myself really liking how Consolas looks and also takes up less screen space. Extending that, custom color schemes similar to Sublime Text would also be great!

I realize that you guys are working hard to consolidate the programming environments for Rhino/Grasshopper. So I would only consider these low priority wishes :)

Best,

Anders

**Comment by saeranv** [comment]
Hear, hear! For me it's an issue of font size. Screen real estate is scarce when you must have your grasshopper, rhino and ghpython windows open all at the same time. Being able to reduce the font size would be a huge help. 

But I also agree with @AndersHoldenDeleuran that this is low priority. 

sv

**Comment by AndersDeleuran** [comment]
Wohoo, this is now possible with the GHPython component in Rhino 6 WIP :)
