### ISSUE TITLE
ghenv.Component.Exposure is read only

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mcneel/ghpython#60]
I'm trying to automate the process of creating/updating userobjects and I noticed that Exposure is a read only properties. Is it possible to change this so one can change the component exposure?

**Comment by piac** [comment]
This property of the Grasshopper SDK is meant as something to be inherited, not as something to be dynamically changed. What are you trying to do exactly? What do you mean by "automating creating userobjects"?
It seems that what you are trying to do might be useful, but this is not the way to address it.

**Comment by piac** [comment]
Please feel free to keep the conversation going

**Comment by mostaphaRoudsari** [comment]
@piac I was writing a component based on your component that iterate between all the components in the file, read the source code, and if the source code is newer than the current version exports the source code and creates a new userobject. I wanted to have the exposure set inside the file so the new userobject ends up in the right position. I just used one of the other properties instead: https://github.com/mostaphaRoudsari/ladybug/blob/master/src/Ladybug_Export%20Ladybug.py#L132

It works fine. Thanks for your explanation.
