### ISSUE TITLE
Provide CodeContext?

### ISSUE THREAD

**Issue by kejace** [mcneel/ghpython#7]
In trying to load the NumPy packages through ghpython, I seem to need the CodeContext of the ironpython instance. Would someone now how to access this, or could you make it available?

**Comment by sbaer** [comment]
this is the same wishlist item as https://github.com/mcneel/rhinopython/issues/1

We still need to figure out how to get numpy installed and running under Rhino

**Comment by piac** [comment]
I will close this issue as from some previous tests NumPy works in 32-bit version of Rhino, including Grasshopper.
Please feel free to re-open in case something comes up.
