### ISSUE TITLE
SDK Grasshopper - Python

### ISSUE THREAD

**Issue by jstarsky** [mcneel/ghpython#72]
Hello
I am searching for SDK grasshopper for Python. Can somebody help to fiend a link or something where i can get the help documentation with all the reference of grasshopper in python

**Comment by piac** [comment]
There is only one SDK documentation for GH at present, the one that you can download by running the _GrasshopperGetSDKDocumentation command in Rhino. It does not contain definitions written in Python, but those methods/classes are accessible from Python.
