### ISSUE TITLE
Question: Call a function from within ghPython component from C# components

### ISSUE THREAD

**Issue by antonszilasi** [mcneel/ghpython#74]
@piac @sbaer 

I have a ghPython component which contains a function, from within my C# components I would like to be able get this ghPython component from the document and call the function within the ghPython component.

Is this possible? If so could you please provide me with some sample code to do so?

Many thanks!

**Comment by piac** [comment]
Hi @antonszilasi 

sorry for the delay in getting back to you. Most of the questions get faster answers on discourse these days.
It is possible to create a System.Delegate of type Func<object,object> (or other more precise types) and assign it to the output of the GhPython component. This method will work in Rhino 5 and in Rhino WIP.

![capture](https://cloud.githubusercontent.com/assets/489572/26115021/2dccf952-3a5f-11e7-889a-d1578a6ca759.PNG)

[pass-functions.zip](https://github.com/mcneel/ghpython/files/1005038/pass-functions.zip)

I hope this helps,

Giulio

--
Giulio Piacentino
for Robert McNeel & Associates
giulio@mcneel.com
